### ISSUE TITLE
需要哪个api呢，或者说怎么获取这个api呢

### ISSUE THREAD

**Issue by gwjl97** [AgaveTech/bob-plugin-openl-translate#1]

**Comment by openlclub** [comment]
您好，感谢您的关注！当前我们正处于小范围封闭内测中，需要更改 `hosts` 配合使用此插件。当性能和稳定性检测完毕后，预计本月底将正式上线公测。欢迎关注我们的 [Telegram 频道](https://t.me/openl_club) 获取最新动向，谢谢！

**Comment by pexu1** [comment]
希望尽快推出deepl的翻译，我愿意参加公测

**Comment by char1eslu** [comment]
期待，不知道是怎么收费的呢

**Comment by openlclub** [comment]
感谢各位的关注与期待！[OpenL](https://openl.club) 已正式开始公测！
